[project]
name = "tinyagents"
version = "0.1.0"
description = "Tiny Agents: LLM + MCP Tools"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "huggingface-hub>=0.31.2",
    "mcp>=1.9.0",
]
